name: 2 - Vulnerability Scan
on:
  workflow_run:
    workflows: ["1 - Reconnaissance"]
    types:
      - completed
jobs:
  nuclei-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Download Recon Artifacts
        uses: actions/github-script@v8
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "sony-live-assets"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync('${{ github.workspace }}/Crypto-live-assets.zip', Buffer.from(download.data));

      - name: Unzip Target File
        run: |
          unzip rockstar-live-assets.zip
          echo "Targets ready for vulnerability scanning:"
          cat current_assets.txt

      - name: Run Nuclei Vulnerability Scan
        id: nuclei_scan
        continue-on-error: true
        uses: projectdiscovery/nuclei-action@v3
        with:
          version: latest
          args: -l current_assets.txt -t cves/,exposures/,misconfiguration/,vulnerabilities/ -o nuclei_results.txt -rl 50 -c 10 -timeout 10

      - name: Report Flaws to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ -s nuclei_results.txt ]; then
            VULNS=$(head -n 15 nuclei_results.txt | tr '\n' '\\n')
            PAYLOAD=$(jq -n --arg c "🚨 **Vulnerability Scan Results for sony.com**\n❌ **Critical Issues Found!**\n\`\`\`text\n$VULNS\n\`\`\`" '{content: $c}')          else
            PAYLOAD=$(jq -n --arg c "🛡️ **Vulnerability Scan Results for sony.com**\n✅ Scan finished. No critical vulnerabilities detected on verified targets." '{content: $c}')
          fi
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               $WEBHOOK_URL
